{
 "title": "ft_services: Overview",
 "description": "Dashboard to overview all fmira's services",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX: CPU usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" = 'nginx') AND $timeFilter",
     "select": [
      [
       { "params": [ "time_idle" ], "type": "field" }
      ],
      [
       { "params": [ "time_iowait" ], "type": "field" }
      ],
      [
       { "params": [ "time_system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "NGINX: Inbound and outbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "NGINX: RAM available (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "NGINX: Disk space used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "Wordpress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wordpress: CPU usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "cpu",
       "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" = 'nginx') AND $timeFilter",
       "select": [
        [
         { "params": [ "time_idle" ], "type": "field" }
        ],
        [
         { "params": [ "time_iowait" ], "type": "field" }
        ],
        [
         { "params": [ "time_system" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "wordpress" }
       ]
      }
     ]
    },
    {
     "title": "Wordpress: Inbound and outbound traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "wordpress" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "nginx" }
       ]
      }
     ]
    },
    {
     "title": "Wordpress: RAM available (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "wordpress" }
       ]
      }
     ]
    },
    {
     "title": "Wordpress: Disk space used (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "wordpress" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL: CPU usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "cpu",
       "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" = 'nginx') AND $timeFilter",
       "select": [
        [
         { "params": [ "time_idle" ], "type": "field" }
        ],
        [
         { "params": [ "time_iowait" ], "type": "field" }
        ],
        [
         { "params": [ "time_system" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "mysql" }
       ]
      }
     ]
    },
    {
     "title": "MySQL: Inbound and outbound traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "mysql" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "nginx" }
       ]
      }
     ]
    },
    {
     "title": "MySQL: RAM available (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "mysql" }
       ]
      }
     ]
    },
    {
     "title": "MySQL: Disk space used (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "mysql" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PHPMyAdmin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHPMyAdmin: CPU usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "cpu",
       "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" = 'nginx') AND $timeFilter",
       "select": [
        [
         { "params": [ "time_idle" ], "type": "field" }
        ],
        [
         { "params": [ "time_iowait" ], "type": "field" }
        ],
        [
         { "params": [ "time_system" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "phpmyadmin" }
       ]
      }
     ]
    },
    {
     "title": "PHPMyAdmin: Inbound and outbound traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 18 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "phpmyadmin" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "nginx" }
       ]
      }
     ]
    },
    {
     "title": "PHPMyAdmin: RAM available (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "phpmyadmin" }
       ]
      }
     ]
    },
    {
     "title": "PHPMyAdmin: Disk space used (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "phpmyadmin" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FTPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "FTPS: CPU usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "cpu",
       "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" = 'nginx') AND $timeFilter",
       "select": [
        [
         { "params": [ "time_idle" ], "type": "field" }
        ],
        [
         { "params": [ "time_iowait" ], "type": "field" }
        ],
        [
         { "params": [ "time_system" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "ftps" }
       ]
      }
     ]
    },
    {
     "title": "FTPS: Inbound and outbound traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "ftps" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "nginx" }
       ]
      }
     ]
    },
    {
     "title": "FTPS: RAM available (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "ftps" }
       ]
      }
     ]
    },
    {
     "title": "FTPS: Disk space used (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "ftps" }
       ]
      }
     ]
    }
   ]
  }
 ]
}